- name: install required package and configuration
  become: true
  hosts: localhost
  roles:
    - role: "{{COMPONENT}}"

#use ansible-pull -U git-url -e COMPONENT=${kubernetes} app/ansible_code/playbook.yml