- name: install required package and configuration
  become: true
  hosts: localhost
  roles:
    - role: "{{COMPONENT}}"
      # vars:
      #   desired_hostname: "web-server-01"
      #   is_cloud_instance: true