#Update your system: sudo apt update && sudo apt upgrade -y
#Install required packages: sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
#Import the Kubernetes GPG key: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
#Add the Kubernetes repository: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
# Update the package index: sudo apt update
# Install kubeadm, kubelet, and kubectl: sudo apt install -y kubelet kubeadm kubectl
# Hold the packages to prevent accidental upgrades: sudo apt-mark hold kubelet kubeadm kubectl
# Disable swap: sudo sed -i '/ swap / s/^\$$.*\$$$/#\\1/g' /etc/fstab and sudo swapoff -a
# Enable required kernel modules and sysctl settings:
# sudo modprobe overlay
# sudo modprobe br_netfilter
# sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
# net.bridge.bridge-nf-call-ip6tables = 1
# net.bridge.bridge-nf-call-iptables = 1
# net.ipv4.ip_forward = 1
# EOF
# sudo sysctl --system
# Initialize the cluster: Run sudo kubeadm init --pod-network-cidr=10.244.0.0/16. This command will output a kubeadm join command for worker nodes.
# Set Up kubectl for the Regular User
# Create the .kube directory and copy the admin config: mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
# Set the correct ownership: sudo chown $(id -u):$(id -g) $HOME/.kube/config
# Deploy a Pod Network Add-on:
# After initialization, deploy a CNI (Container Network Interface) plugin like Flannel to enable communication between pods: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
# Your Kubernetes master node is now ready. Use the kubeadm join command provided in the kubeadm init output to add worker nodes to the cluster.

- name: install pre-request packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: creating apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /tmp/kubernetes.key
    mode: "0644"

- name: Convert GPG key to binary format and save to keyring
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: create kubernetes repository file
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: kubernetes.list

- name: install kubeadm, kubelet and kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

# - name: disable swap
#   ansible.builtin.command:
#     # cmd: sudo sed -i '/ swap / s/^\$$.*\$$$/#\\1/g' /etc/fstab and sudo swapoff -a
#     cmd: sed -i '/ swap / s/^\$$.*\$$$/#\\1/g' /etc/fstab and sudo swapoff -a
- name: Disable swap
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none   

# - name: enable kernal modules
#   ansible.builtin.command:
#     argv:
#       - modprobe overlay
#       - modprobe br_netfilter
- name: Enable kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter   

- name: enable network setting
  ansible.builtin.copy:
    src: kubernetes.conf
    dest: /etc/sysctl.d/kubernetes.conf
    mode: '0644'
    owner: root
    group: root

- name: initialize the cluster
  ansible.builtin.command:
    cmd: sudo kubeadm init --pod-network-cidr=10.244.0.0/16

- name: making setup for kubernetes
  ansible.builtin.command:
    argv:
      - mkdir -p $HOME/.kube
      - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      - chown $(id -u):$(id -g) $HOME/.kube/config

- name: install plugins
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml