# sudo swapoff -a
# sudo sed -i '/ swap / s/^\$$.*\$$$/#\\1/g' /etc/fstab

# - name: disable swap
#   ansible.builtin.shell: sudo sed -i '/ swap / s/^\$$.*\$$$/#\\1/g' /etc/fstab && sudo swapoff -a
#   args:
#     executable: /bin/bash

- name: Disable swap
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none 

#sudo hostnamectl set-hostname master-node

- name: Set hostname for kubernetes
  ansible.builtin.hostname:
    name: "{{ k8s_hostname }}"          #value comes from default/main.yml
    use: systemd
  become: true

# - name: Update /etc/hosts to prevent sudo lag
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     regexp: '^127\.0\.1\.1'
#     line: "127.0.1.1 {{ hostname }}"
#     owner: root
#     group: root
#     mode: '0644'
#   become: true

# - name: Ensure cloud-init does not overwrite hostname (Cloud instances only)
#   ansible.builtin.lineinfile:
#     path: /etc/cloud/cloud.cfg
#     regexp: '^preserve_hostname:'
#     line: 'preserve_hostname: true'
#   become: true
#   when: is_cloud_instance | bool

#sudo tee /etc/modules-load.d/kubernetes.conf <<EOF
# overlay
# br_netfilter
# EOF

- name: add modules into kubernetes
  ansible.builtin.template:
    src: modules.conf
    dest: /etc/modules-load.d/kubernetes.conf

# sudo modprobe overlay
# sudo modprobe br_netfilter

- name: Enable kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

#we can use below task in place of above two task "add modules into kubernetes" and "Enable kernel modules"
#but problem with below task is, it will create file name randamely "<module>.conf" not specific "kubernetes.conf"
#that's why we are using above 2 tasks to add kernal module into kubernetes
#persistent: present automatically creates /etc/modules-load.d/<module>.conf.
# - name: Enable and persist kernel modules
#   community.general.modprobe:
#     name: "{{ item }}"
#     state: present
#     persistent: present
#   loop:
#     - overlay
#     - br_netfilter

# sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
# net.bridge.bridge-nf-call-ip6tables = 1
# net.bridge.bridge-nf-call-iptables = 1
# net.ipv4.ip_forward = 1
# EOF
# sudo sysctl --system
#On Ubuntu 24.04, the net.bridge parameters often fail if the br_netfilter kernel module isn't loaded first.

- name: Ensure br_netfilter module is loaded
  community.general.modprobe:
    name: br_netfilter
    state: present
  become: true

#Using sysctl_set: true (as added above) is a safety net—it tells Ansible to verify the value was actually set in the kernel, not just written to a file.

- name: Enable networking sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    reload: true
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
  become: true

# sudo apt install -y containerd

- name: install containerd
  ansible.builtin.apt:
    name:
      - containerd
    state: present
    update_cache: yes

# - name: configure and enabled containerd
#   ansible.builtin.command:
#     cmd: |
#       sudo mkdir -p /etc/containerd
#       containerd config default |sudo tee /etc/containerd/config.toml
#       set -i 's/SystemdCgroup=false/SystemdCgroup=true/' >> /etc/containerd/config.toml
#       sudo systemctl restart containerd
#       sudo systemctl enable containerd

# sudo mkdir -p /etc/containerd

- name: create containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

# containerd config default |sudo tee /etc/containerd/config.toml

- name: generate containerd config default file
  ansible.builtin.shell: "containerd config default > /etc/containerd/config.toml"
  args: 
    creates: /etc/containerd/config.toml

# set -i 's/SystemdCgroup=false/SystemdCgroup=true/' >> /etc/containerd/config.toml
#regexp
# ^abc → Matches lines starting with "abc"
# xyz$ → Matches lines ending with "xyz"
# ^ and $ → Ensures whole line match
# \s* → Matches zero or more spaces
# - name: enable SystemCgroup in containerd
#   ansible.builtin.replace:
#     path: /etc/containerd/config.toml
#     regexp: '^SystemdCgroup\s*=\s*false$'
#     replace: '^SystemdCgroup\s*=\s*true$'

- name: enable SystemCgroup in containerd
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup\s*=\s*false$'
    line: 'SystemdCgroup = true'

# sudo systemctl restart containerd
# sudo systemctl enable containerd 

- name: start and enabled containerd
  ansible.builtin.systemd_service:
    name: containerd
    state: started
    enabled: true

# sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

- name: install pre-request packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

# curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: creating apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /tmp/kubernetes.key
    mode: "0644"
- name: Convert GPG key to binary format and save to keyring
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: create kubernetes repository file
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: kubernetes.list

# sudo apt update
# sudo apt install -y kubelet kubeadm kubectl

- name: install kubeadm, kubelet and kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

# sudo apt-mark hold kubelet kubeadm kubectl

- name: mark hold
  ansible.builtin.command:
    cmd: sudo apt-mark hold kubelet kubeadm kubectl

# sudo kubeadm init --pod-network-cidr=192.168.0.0/16  

- name: initialize the cluster
  ansible.builtin.command:
    cmd: sudo kubeadm init --pod-network-cidr=192.168.0.0/16

# mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
# sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: making setup for kubernetes
  ansible.builtin.command:
    argv:
      - mkdir -p $HOME/.kube
      - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      - chown $(id -u):$(id -g) $HOME/.kube/config

# kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml

- name: install network plugins
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml