name: make deployment to expense app using docker containers
on:
  push:
    branches: ["main"]
# env:
#   FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
defaults:
  run:
    shell: bash
jobs:
  compile:
    runs-on: ['workStation01']
    steps:
      - name: checkout git repo code
        #uses: actions/checkout@v4
        uses: actions/checkout@v5
      - name: compile code
        run: echo 'code is compiled'
  create_infra:
    runs-on: ['workStation01']
    needs: ['compile']
    steps:
      - name: checkout git repo code
        #uses: actions/checkout@v4
        uses: actions/checkout@v5
      # - name: setup terraform
      #   uses: hashicorp/setup-terraform@v3
      - name: creating worker01 server for deployment
        #run: bash app/terraform_code/create.sh
        run: echo 'infra is already created'
  configure_packages:
    runs-on: ['workStation01']
    #environment: USER_NAME
    needs: ['create_infra']
    steps:
      - name: checkout git repo code
        #uses: actions/checkout@v4
        uses: actions/checkout@v5
      # - name: setup python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12.3'
      - name: configure source code
        env:
          ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          USER: ${{ secrets.REPO_USER_NAME }}
          SSH_PASS: ${{ secrets.WORKER01_SSH_PASS }}
        run: bash app/ansible_code/init.sh $USER $ACCESS_TOKEN kubernetes $SSH_PASS
